version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - "5432:5432"
    restart: always
  
  app:
    build: .
    container_name: app
    ports:
      - "3333:3333"
    restart: always
    depends_on:
      - postgres